<?php
/**
 * @file
 * KDB custom feeds module.
 */

 /**
 * Implements hook_views_data_alter().
 */
function kdb_feeds_views_data() {
  $data = array();
  $data['migrate_map_kdbeventfeedimport']['table']['group']  = t('Kdb event feed import migrate table');
  $data['migrate_map_kdbeventfeedimport']['table']['base'] = array(
    'field' => 'sourceid1',
    'title' => t('Kdb event feed import migrate table'),
    'help' => t("Custom table created by migrate module used for storing migrated content."),
    'weight' => -10,
  );

  $data['migrate_map_kdbeventfeedimport']['table']['join'] = array(
    'node' => array(
      'handler' => 'views_join',
      'left_table' => 'node_revisions',
      'left_field' => 'nid',
      'field' => 'destid1',
     ),
  );

  $data['migrate_map_kdbeventfeedimport']['sourceid1'] = array(
    'title' => t('sourceid1'),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
  );

  $data['migrate_map_kdbeventfeedimport']['destid1'] = array(
    'title' => t('destid1'),
    'relationship' => array(
      'base' => 'node',
      'base field' => 'nid',
      'handler' => 'views_handler_relationship',
      'label' => t('Node'),
    ),
  );
  return $data;
}

include_once('kdb_feeds.features.inc');
