<?php

/**
 * Implementation of hook_preprocess().
 */
function kdb_event_preprocess_views_view_fields(&$vars) {
  // Add is_today variable if an event occours on the current day.
  // @see ding_event_preprocess_views_view_fields
  if ($vars['view']->name == 'kdb_event_list' and isset($vars['fields']['field_datetime_value'])) {
    $vars['is_today'] = date_format_date(date_make_date($vars['fields']['field_datetime_value']->raw), 'custom', 'Ymd') == date('Ymd') ? 'today' : '';
  }
}


include_once('kdb_event.features.inc');
