<?php
/**
 * @file
 * Base Copenhagen module
 *
 * Provides date formats and other code shared by all Copenhagen Ding! modules.
 */

/**
 * Implements hook_form_alter().
 */
function kdb_base_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'node-form') {
    // Make the author field on node forms required - no anonymous
    // authors allowed.
    $form['author']['name']['#required'] = TRUE;
    $form['author']['name']['#description'] = 'Skriv brugernavnet på ejeren af indlægget.';
  }
}

/**
 * Implements hook_imagecache_default_presets_alter().
 */
function kdb_base_imagecache_default_presets_alter(&$presets) {
  // Remove desaturation action from default ding_tabroll preset.
  if (isset($presets['460_240_crop'])) {
    foreach ($presets['460_240_crop']['actions'] as $key => $action) {
      if ($action['action'] == 'imagecache_desaturate') {
        unset($presets['460_240_crop']['actions'][$key]);
      }
    }
  }
}
